### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by Linuus** [varvet/godmin-redactor#1]
It would be nice if you could pass options to the redactor plugin, either via data attributes or exposing the `initializeRedactor` function and use that.

**Comment by kindell** [comment]
Agree on the passing of options. Looking forward to a PR.

**Comment by kindell** [comment]
Fixed in [latest release](https://github.com/varvet/godmin-redactor/blob/master/CHANGELOG.md#011---2015-03-12).

**Comment by Linuus** [comment]
![cheering_minions](https://cloud.githubusercontent.com/assets/379823/6620831/337a26d6-c8d3-11e4-8783-f532e11b4cc0.gif)
